py_binary(
    name = "labelflip",
    deps = ['//:ymir'],
    srcs = ["labelflip.py", "metrics.py", "datasets.py"],
    main = "labelflip.py",
)

py_binary(
    name = "freerider",
    deps = ['//:ymir'],
    srcs = ["freerider.py", "metrics.py", "datasets.py"],
    main = "freerider.py",
)

py_binary(
    name = "grid_search",
    deps = ['//:ymir'],
    srcs = ["grid_search.py", "metrics.py", "datasets.py"],
    main = "grid_search.py",
)

py_binary(
    name = "mouther",
    deps = ['//:ymir'],
    srcs = ["mouther.py", "metrics.py", "datasets.py"],
    main = "mouther.py",
)