py_binary(
  name = "fedavg",
  deps = ['//:ymir'],
  srcs = ["fedavg.py"],
  main = "fedavg.py",
)

py_binary(
  name = "fedmax",
  deps = ['//:ymir'],
  srcs = ["fedmax.py"],
  main = "fedmax.py",
)

py_binary(
  name = "fedprox",
  deps = ['//:ymir'],
  srcs = ["fedprox.py"],
  main = "fedprox.py",
)