py_binary(
    name = "compression",
    deps = ['//:ymir'],
    srcs = ["compression.py", "utils.py"],
    main = "compression.py",
)

py_binary(
    name = "tutelage",
    deps = ['//:ymir'],
    srcs = ["tutelage.py", "utils.py"],
    main = "tutelage.py",
)